config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "application/L4" => "application#L4"
 # root "application#L4"
  
  
  get 'top/main'
  post 'top/login'
  root 'top#main'
  get'top/logout'
  
  
  # 新規ユーザー登録のルート
  get 'users/new', to: 'users#new', as: 'new_user'
  post 'users', to: 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # ユーザーログイン時にパスワードを暗号化して比較する
  def self.authenticate(uid, pass)
    user = find_by(uid: uid)
    return nil unless user

    # BCryptを使用してパスワードを比較
    return user if BCrypt::Password.new(user.pass) == pass

    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def L4
        session[:c] ||= 0
        session[:c] = session[:c].to_i + 1
        render plain: session[:c]
    end
    

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    #@user.pass = BCrypt::Password.create(params[:user][:pass]) # パスワードをハッシュ化
    @user.pass = BCrypt::Password.create(user_params[:pass]) # user_params[:pass]を使用

    if @user.save
      redirect_to root_path, notice: 'ユーザー登録が完了しました'
    else
      #render :new
      render :new and return
    end
  end

  private

  def user_params
    params.require(:user).permit(:uid, :pass)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid].nil?
      render 'login'
    else
      @user = User.find_by(uid: session[:login_uid])
      @hashed_pass = @user.pass if @user  # ハッシュ値を取得
      render 'main'
    end
  end

  # ログイン処理
  def login
    # ユーザーをUIDで検索
    user = User.find_by(uid: params[:uid])

    # ユーザーが存在し、入力されたパスワードとユーザーのパスワードが一致するかを確認
    if user && BCrypt::Password.new(user.pass) == params[:pass]
      # ログイン成功時、セッションにユーザーIDを保存
      session[:login_uid] = user.uid
      redirect_to action: :main
    else
      # ログイン失敗時、エラーメッセージを表示
      flash.now[:alert] = 'IDまたはパスワードが間違っています。'
      render 'login'  
    end
  end

  # ログアウト処理
  def logout
    # セッションからユーザーIDを削除
    session.delete(:login_uid)
    redirect_to action: :main
  end
  
  # ユーザー新規登録画面を表示
  def new
    @user = User.new  # ユーザー登録の新しいインスタンスを作成
    render 'new_user' # 修正: 'new_user'に変更
  end
  
  # 新規ユーザーを作成
  def create_user
    uid = params[:user][:uid]
    pass = params[:user][:pass]

    # パスワードを暗号化して保存
    encrypted_pass = BCrypt::Password.create(pass)
    @user = User.new(uid: uid, pass: encrypted_pass)

    if @user.save
      redirect_to root_path, notice: "ユーザー登録が完了しました"
    else
      render 'new_user', status: :unprocessable_entity
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.pass = BCrypt::Password.create(params[:user][:pass]) # パスワードをハッシュ化して保存

    if @user.save
      session[:login_uid] = @user.uid  # ユーザーIDをセッションに保存
      redirect_to top_main_path, notice: 'ユーザー登録が完了しました。'
    else
      render :new and return  # エラーが発生した場合にだけ render を呼び出す
    end
  end

  private

  def user_params
    params.require(:user).permit(:uid, :pass)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h1>ログイン失敗!</h1>
<p>ユーザーIDまたはパスワードが間違っています。</p>
<%= link_to '戻る', top_main_path %>

app/views/top/login.html.erb
<h1>ログイン</h1>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>



<%= form_with url: '/top/login', method: :post, local: true do |f| %>
<%= f.label :uid, 'ユーザーID' %>
<%= f.text_field :uid %>
<%= f.label :pass, 'パスワード' %>
<%= f.password_field :pass %>
<%= f.submit 'ログイン' %>
<a href="<%= new_user_path %>">新規ユーザー登録</a>
<% end %>

app/views/top/main.html.erb
<h1>ログイン中です</h1>
<p>ようこそ、<%= session[:login_uid] %> さん！</p>
<p>ハッシュ値: <%= @hashed_pass %></p>

<p>
    <%= link_to"ログアウト",top_logout_path %>
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>新規ユーザー登録</h1>
<%= form_with scope: :user, url: users_path, local: true do |f| %>
  <%= f.label :uid, 'ユーザーID' %>
  <%= f.text_field :uid %>

  <%= f.label :pass, 'パスワード' %>
  <%= f.password_field :pass %>

  <%= f.submit '登録' %>
<% end %>